[project]
name = "clappia-mcp"
version = "1.0.0"
description = "MCP server that allows operations at Clappia"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.8.0",
    "modelcontextprotocol>=0.1.0",
]